[profile.default]
solc = '0.8.19'
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

fs_permissions = [{ access = "read-write", path = "./"}]

[etherscan]
arbitrumgoerli = { key = "${ARBITRUMGOERLI_ETHERSCAN_API_KEY}", url = "${ARBITRUMGOERLI_EXPLORER_API_URL}" }
opgoerli = { key = "${OPGOERLI_ETHERSCAN_API_KEY}", url = "${OPGOERLI_EXPLORER_API_URL}" }
arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", url = "${ARBITRUM_EXPLORER_API_URL}" }