
// generated by foundry_ts/methods/ccmanager/genCode.ts
// Path: script/foundry_scripts/relay/deployNewRelayImp.s.sol
import { addOperation } from "../../utils/config";
import { ccmanager_deploy_json } from "../../utils/const";
import { set_env_var, foundry_wrapper } from "../../foundry";
import { checkArgs } from "../../helper";
import { setupDeployJson } from "../../utils/setupDeployJson";
import { verifyContract } from "../verifyContract";
import { getContractAddress } from "../../utils/getDeployData";
import { ethers } from "ethers";
import { writeToProposal } from "../../utils/writeProposal";

// current file name
const method_name = "deployNewRelayImpl";

export function deployNewRelayImplWithArgv(argv: any) {
    const required_flags = ["env", "network", "broadcast"];
    checkArgs(method_name, argv, required_flags);
    deployNewRelayImpl(argv.env, argv.network, argv.broadcast, argv.simulate, argv.multisig);
}

export function deployNewRelayImpl(env: string, network: string, broadcast: boolean, simulate: boolean, multisig: boolean) {
    

    set_env_var(method_name, "env", env);
    set_env_var(method_name, "network", network);
    set_env_var(method_name, "broadcast", broadcast.toString());
    foundry_wrapper(method_name, broadcast, simulate);

    if (multisig) {
        const relayAddress = getContractAddress(env, network, "CCRelay", false);
        const proxy = getContractAddress(env, network, "CCRelay", true);
        const filename = "upgradeToNewRelayImpl";
        const value = "0";
        const method = "upgradeTo(address)";
        // encode packed bytes dstRelayAddress, relayAddress
        const params = [relayAddress];
        writeToProposal(filename, env, network, proxy, value, method, params);
    }

    verifyContract(env, network, "CCRelay", false, undefined, "0.8.19", simulate);

}

addOperation(method_name, deployNewRelayImplWithArgv);
