
// generated by foundry_ts/methods/ccmanager/genCode.ts
// Path: script/foundry_scripts/ccmanager/deployNewManagerImlp.s.sol
import { addOperation } from "../../utils/config";
import { ccmanager_deploy_json } from "../../utils/const";
import { set_env_var, foundry_wrapper } from "../../foundry";
import { checkArgs } from "../../helper";
import { setupDeployJson } from "../../utils/setupDeployJson";
import { getContractAddress } from "../../utils/getDeployData";
import { writeToProposal } from "../../utils/writeProposal";
import { verifyContract } from "../verifyContract";

// current file name
const method_name = "deployNewManagerImpl";

export function deployNewManagerImplWithArgv(argv: any) {
    const required_flags = ["env", "network", "role", "broadcast"];
    checkArgs(method_name, argv, required_flags);
    deployNewManagerImpl(argv.env, argv.network, argv.role, argv.broadcast, argv.simulate, argv.multisig);
}

export function deployNewManagerImpl(env: string, network: string, role: string, broadcast: boolean, simulate: boolean, multisig: boolean) {
    

    set_env_var(method_name, "env", env);
    set_env_var(method_name, "network", network);
    set_env_var(method_name, "role", role);
    set_env_var(method_name, "broadcast", broadcast.toString());
    foundry_wrapper(method_name, broadcast, simulate);

    const contract = role === "ledger" ? "LedgerCCManager" : "VaultCCManager";

    if (multisig) {
        const managerAddress = getContractAddress(env, network, contract, false);
        const proxy = getContractAddress(env, network, contract, true);
        const filename = "upgradeToNewManagerImpl";
        const value = "0";
        const method = "upgradeTo(address)";
        // encode packed bytes dstManagerAddress, managerAddress
        const params = [managerAddress];
        writeToProposal(filename, env, network, proxy, value, method, params);
    }


    verifyContract(env, network, contract, false, undefined, "0.8.19", simulate);

}

addOperation(method_name, deployNewManagerImplWithArgv);
