
// generated by foundry_ts/methods/ccmanager/genCode.ts
// Path: script/foundry_scripts/simulate.s.sol
import { addArgvType, addOperation } from "../utils/config";
import { ccmanager_deploy_json } from "../utils/const";
import { set_env_var, foundry_wrapper } from "../foundry";
import { checkArgs } from "../helper";
import { setupDeployJson } from "../utils/setupDeployJson";

// current file name
const method_name = "simulate";

addArgvType("string", "data");

export function simulateWithArgv(argv: any) {
    const required_flags = ["network", "to", "data"];
    checkArgs(method_name, argv, required_flags);
    simulate(argv.network, argv.to, argv.data, argv.broadcast, argv.simulate);
}

export function simulate(network: string, to: string, data: string, broadcast: boolean, simulate: boolean) {
    

    set_env_var(method_name, "network", network);
    set_env_var(method_name, "to", to);
    set_env_var(method_name, "data", data);
    foundry_wrapper(method_name, broadcast, simulate);

}

addOperation(method_name, simulateWithArgv);
