
// generated by foundry_ts/methods/ccmanager/genCode.ts
// Path: foundry_scripts/ccmanager/setCCManagerLedgerManager.s.sol
import { addOperation } from "../../utils/config";
import { ccmanager_deploy_json } from "../../utils/const";
import { set_env_var, foundry_wrapper } from "../../foundry";
import { checkArgs } from "../../helper";
import { setupDeployJson } from "../../utils/setupDeployJson";

// current file name
const method_name = "setCCManagerLedgerManager";

export function setCCManagerLedgerManagerWithArgv(argv: any) {
    const required_flags = ["env", "network", "ledgerNetwork"];
    checkArgs(method_name, argv, required_flags);
    setCCManagerLedgerManager(argv.env, argv.network, argv.ledgerNetwork, argv.broadcast, argv.simulate);
}

export function setCCManagerLedgerManager(env: string, network: string, ledgerNetwork: string, broadcast: boolean, simulate: boolean) {
    

    set_env_var(method_name, "env", env);
    set_env_var(method_name, "network", network);
    set_env_var(method_name, "ledgerNetwork", ledgerNetwork);
    foundry_wrapper(method_name, broadcast, simulate);

}

addOperation(method_name, setCCManagerLedgerManagerWithArgv);
