
// generated by foundry_ts/methods/ccmanager/genCode.ts
// Path: foundry_scripts/ccmanager/setCCManagerTokenDecimal.s.sol
import { addOperation } from "../../utils/config";
import { ccmanager_deploy_json } from "../../utils/const";
import { set_env_var, foundry_wrapper } from "../../foundry";
import { checkArgs } from "../../helper";
import { setupDeployJson } from "../../utils/setupDeployJson";

// current file name
const method_name = "setCCManagerTokenDecimal";

export function setCCManagerTokenDecimalWithArgv(argv: any) {
    const required_flags = ["env", "network", "tokenNetwork"];
    checkArgs(method_name, argv, required_flags);
    setCCManagerTokenDecimal(argv.env, argv.network, argv.tokenNetwork, argv.broadcast, argv.simulate);
}

export function setCCManagerTokenDecimal(env: string, network: string, tokenNetwork: string, broadcast: boolean, simulate: boolean) {
    

    set_env_var(method_name, "env", env);
    set_env_var(method_name, "network", network);
    set_env_var(method_name, "tokenNetwork", tokenNetwork);
    foundry_wrapper(method_name, broadcast, simulate);

}

addOperation(method_name, setCCManagerTokenDecimalWithArgv);
