
// generated by foundry_ts/methods/ccmanager/genCode.ts
// Path: foundry_scripts/ccmanager/setCCManagerTokenDecimal.s.sol
import { addArgvType, addOperation } from "../../utils/config";
import { ccmanager_deploy_json } from "../../utils/const";
import { set_env_var, foundry_wrapper } from "../../foundry";
import { checkArgs } from "../../helper";
import { setupDeployJson } from "../../utils/setupDeployJson";
import { getChainId } from "../../utils/envUtils";
import { getTokenDecimal } from "../../utils/getEnvConfig";
import { writeToProposal } from "../../utils/writeProposal";
import { getContractAddress } from "../../utils/getDeployData";


// current file name
const method_name = "setCCManagerTokenDecimal";

export function setCCManagerTokenDecimalWithArgv(argv: any) {
    const required_flags = ["env", "network", "tokenNetwork"];
    checkArgs(method_name, argv, required_flags);
    setCCManagerTokenDecimal(argv.env, argv.network, argv.tokenNetwork, argv.broadcast, argv.simulate, argv.multisig);
}

export function setCCManagerTokenDecimal(env: string, network: string, tokenNetwork: string, broadcast: boolean, simulate: boolean, multisig: boolean = false) {
    
    if (multisig) {
        const filename = "setCCManagerTokenDecimal";
        const value = "0";
        const method = "setTokenDecimal(bytes32,uint256,uint128)";
        const address = getContractAddress(env, network, "LedgerCCManager", true);
        const chainId = getChainId(tokenNetwork);
        const tokenDecimal = getTokenDecimal(env, tokenNetwork, "USDC");
        const tokenHash = tokenDecimal['tokenHash'];
        const decimal = tokenDecimal['decimals'];
        const params = [tokenHash, chainId.toString(), decimal.toString()];
        writeToProposal(filename, env, network, address, value, method, params);

        return;
    }

    set_env_var(method_name, "env", env);
    set_env_var(method_name, "network", network);
    set_env_var(method_name, "tokenNetwork", tokenNetwork);
    foundry_wrapper(method_name, broadcast, simulate);

}

addOperation(method_name, setCCManagerTokenDecimalWithArgv);
